### GET all locations for dashboard page
GET http://localhost:3000/api/dashboard/locations
Content-Type: application/json; charset=utf-8

### GET all measures for dashboard page
GET http://localhost:3000/api/dashboard/sensor/1/measures?period=last-day
Content-Type: application/json; charset=utf-8