### GET all locations for dashboard page
GET http://localhost:3000/api/dashboard/locations
Content-Type: application/json; charset=utf-8

### GET all measures for dashboard page
GET http://localhost:3000/api/dashboard/sensor/-6/measures?period=last-week
Content-Type: application/json; charset=utf-8