### GET all sensors
GET http://localhost:3000/api/sensors
Content-Type: application/json; charset=utf-8

### GET sensor by sensorid
GET http://localhost:3000/api/sensors/3
Content-Type: application/json; charset=utf-8

### GET sensor by sensorid (error)
GET http://localhost:3000/api/sensors/-1
Content-Type: application/json; charset=utf-8